/**
 * Render the worked year as SQL, for loading into a real D1 database.
 *
 * D1 has no way to run the seed module directly: `seed()` is TypeScript
 * against the SqlDatabase interface, and wrangler speaks SQL files. Rather
 * than write the fixture out twice — once as code, once as SQL, with the two
 * drifting the first time anyone touches either — this builds the database
 * locally with the real `migrate()` and `seed()` and then dumps what they
 * produced.
 *
 *   npx vite-node scripts/seed-sql.ts > seed.sql
 *   npx wrangler d1 execute bedrock --remote --file=seed.sql
 *
 * Two orderings matter, and both are the database's rules rather than this
 * script's preference:
 *
 *   - `budgets` rows go in before their `budget_years` row, because an
 *     approved year refuses new lines.
 *   - `reconciliations` go in open and are marked balanced at the end, because
 *     a balanced reconciliation refuses changes to what has cleared.
 *
 * `audit_log` is deliberately not dumped. The triggers write it on insert, so
 * copying the rows across would double every entry. Letting them regenerate is
 * also the more faithful result: the trail in D1 is one the database wrote,
 * not one this script asserted.
 */

import { migrate } from '../src/server/db/migrate'
import { openNodeDatabase } from '../src/server/db/node-sqlite'
import { RESTORE_ORDER } from '../src/server/repo/handoff'
import { ASSEMBLY_ID, SEED_YEAR, seed } from '../src/server/seed'
import { loadFunds } from '../src/server/repo/funds'

/**
 * Insertion order, read from the one place that defines it.
 *
 * `audit_log` is filtered out: the triggers write it as the rows arrive, so
 * dumping it too would double every entry.
 */
const TABLES = RESTORE_ORDER.filter((t) => t !== 'audit_log')

function literal(value: unknown): string {
  if (value === null || value === undefined) return 'NULL'
  if (typeof value === 'number') return String(value)
  if (typeof value === 'bigint') return value.toString()
  return `'${String(value).replace(/'/g, "''")}'`
}

const db = openNodeDatabase(':memory:')
await migrate(db)
await seed(db)

const out: string[] = []
out.push('-- Generated by scripts/seed-sql.ts. Do not edit by hand.')
out.push('-- The worked year of 183 B.E., as produced by src/server/seed.ts.')
out.push('')
// The audit triggers abort any write with no actor set, exactly as they do in
// the application. The seed is no exception, here or there.
out.push(
  "INSERT INTO audit_actor (id, actor) VALUES (1, 'seed')\n" +
    '  ON CONFLICT (id) DO UPDATE SET actor = excluded.actor;',
)
out.push('')

for (const table of TABLES) {
  const rows = await db.all<Record<string, unknown>>(`SELECT * FROM ${table}`)
  if (rows.length === 0) continue

  out.push(`-- ${table}: ${rows.length} row${rows.length === 1 ? '' : 's'}`)
  const columns = Object.keys(rows[0])
  for (const row of rows) {
    const values = columns.map((c) =>
      // A balanced reconciliation refuses to have its ticks changed, so it
      // goes in open and is closed once its items are loaded.
      table === 'reconciliations' && c === 'status' ? "'open'" : literal(row[c]),
    )
    out.push(
      `INSERT INTO ${table} (${columns.join(', ')}) VALUES (${values.join(', ')});`,
    )
  }
  out.push('')
}

const balanced = await db.all<{ id: string; status: string }>(
  "SELECT id, status FROM reconciliations WHERE status = 'balanced'",
)
if (balanced.length > 0) {
  out.push('-- Now that every cleared item is loaded, close the statements.')
  for (const r of balanced) {
    out.push(
      `UPDATE reconciliations SET status = 'balanced' WHERE id = ${literal(r.id)};`,
    )
  }
  out.push('')
}

const sql = out.join('\n')

// ── prove the dump before handing it over ────────────────────────────────────
//
// Replay it into a second empty database and check it lands on the same books.
// A dump that loads without error but reproduces different figures is the
// failure worth catching here rather than in production: the ordering rules
// above are the database's, and if one is ever violated the symptom is a row
// silently rejected, not a crash.
const replay = openNodeDatabase(':memory:')
await migrate(replay)
for (const chunk of sql.split(/;\r?\n/)) {
  // Comment lines are stripped rather than the chunk being skipped for
  // starting with one: each statement is preceded by its table's header
  // comment, so skipping on that basis silently drops every first insert.
  const statement = chunk
    .split('\n')
    .filter((line) => !line.trimStart().startsWith('--'))
    .join('\n')
    .trim()
  if (statement.length === 0) continue
  try {
    await replay.run(statement)
  } catch (error) {
    console.error(`\nThe generated SQL was rejected:\n  ${statement.slice(0, 160)}`)
    console.error(`  ${String(error)}`)
    process.exit(1)
  }
}

const [before, after] = await Promise.all([
  loadFunds(db, ASSEMBLY_ID, SEED_YEAR),
  loadFunds(replay, ASSEMBLY_ID, SEED_YEAR),
])
const shape = (v: Awaited<ReturnType<typeof loadFunds>>) =>
  JSON.stringify({
    onHand: v.onHandCents,
    funds: v.funds.map((f) => [f.key, f.balanceCents]),
    owed: v.owedUpwardCents,
  })

if (shape(before) !== shape(after)) {
  console.error('\nThe replayed database does not match the seeded one.')
  console.error(`  seeded:   ${shape(before)}`)
  console.error(`  replayed: ${shape(after)}`)
  process.exit(1)
}

const rowCount = async (d: typeof db, table: string) =>
  (await d.get<{ n: number }>(`SELECT COUNT(*) AS n FROM ${table}`))!.n

for (const table of TABLES) {
  const a = await rowCount(db, table)
  const b = await rowCount(replay, table)
  if (a !== b) {
    console.error(`\n${table}: seeded ${a} rows, replayed ${b}.`)
    process.exit(1)
  }
}

// audit_log is checked by property, not by count, and the two will not match.
//
// Seeding performs state transitions — a report is built, then finalised,
// then presented; its transactions are locked — and each is an audited UPDATE.
// Loading a dump of the finished state performs only inserts, so the trail it
// grows is shorter. That is the truthful record of what happened to THIS
// database, and manufacturing the missing entries would be writing a history
// that did not occur into the one table whose whole value is that it did.
//
// What must hold is that nothing arrived unrecorded.
const unlogged = await replay.get<{ n: number }>(
  `SELECT COUNT(*) AS n FROM transactions t
    WHERE NOT EXISTS (SELECT 1 FROM audit_log a
                       WHERE a.entity = 'transactions' AND a.entity_id = t.id
                         AND a.action = 'insert')`,
)
if ((unlogged?.n ?? 0) > 0) {
  console.error(`\n${unlogged!.n} transactions arrived without an audit entry.`)
  process.exit(1)
}
const blankActor = await replay.get<{ n: number }>(
  "SELECT COUNT(*) AS n FROM audit_log WHERE TRIM(actor) = ''",
)
if ((blankActor?.n ?? 0) > 0) {
  console.error(`\n${blankActor!.n} audit entries have no actor.`)
  process.exit(1)
}

console.error(
  `Verified: ${sql.split('\n').length} lines replay to the same books ` +
    `(${shape(after)}); every transaction logged by the triggers on arrival.`,
)

db.close()
replay.close()
process.stdout.write(sql)
